### ISSUE TITLE
this hcap bypass in python

### ISSUE THREAD

**Issue by cChimney** [liltoba/Hcapplugin#1]
Yo i been trying this out a lil bit but how do i get the captchakey from this? Doing captchakey = asyncio.run(Async_hCaptcha.Hcaptcha_Handler(host,sitekey)) rn but it's giving

key = payload['key']
KeyError: 'key'

**Comment by cChimney** [comment]
{'c': {'type': 'hsw', 'req': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjoyLCJ0IjoidyIsImQiOiJ5SHR3elVUQldNRzIwNi9QR2hZR0J1OE5MUjNhWmg1bEtaVW5zZU9aN0t6VVRrSXg5TDdyNGpqaWdydUpUaXB3K2JPTUZQVWMzMFpidG5nNm8zMmNKNS94SUFkMDBFUzZ4dDBIbG9xWXFpeWZaRENKRFY3NlNFVEwwQjJITEdFRkpRUVEwSDN0WFlNWFlmY3c1VXJTZ21qSjdmWGdhYUhORWNuUEQwS0ZjNllyQldaNDd3MjQxcE5XZWc9PUVDR1ZwUkk1eVJieDJYd08iLCJsIjoiaHR0cHM6Ly9uZXdhc3NldHMuaGNhcHRjaGEuY29tL2MvOTYzZTQ2YjciLCJlIjoxNjM2MzgxMjUzfQ.4wgul2oJ8hJH8v2HXgTxpkV5IJrUz4riwJl3RkPe-gs'}, 'success': False, 'error-codes': []}

Getting this if i print payload and there aint a "key" in there.

**Comment by atkn1337** [comment]
data = {
        'sitekey':sitekey,
        'host':host,
        'hl': 'en',
        'motionData': '{}',
        'n': n,
        'c': '{"type":"hsw","req":"' + req + '"}'
    }
